# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import matecat_api
from matecat_api.api.quality_report_api import QualityReportApi  # noqa: E501
from matecat_api.rest import ApiException


class TestQualityReportApi(unittest.TestCase):
    """QualityReportApi unit test stubs"""

    def setUp(self):
        self.api = QualityReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_jobs_id_job_password_quality_report_get(self):
        """Test case for api_v2_jobs_id_job_password_quality_report_get

        Quality report  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
