# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import matecat_api
from matecat_api.models.body13 import Body13  # noqa: E501
from matecat_api.rest import ApiException


class TestBody13(unittest.TestCase):
    """Body13 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody13(self):
        """Test Body13"""
        # FIXME: construct object with mandatory attributes with example values
        # model = matecat_api.models.body13.Body13()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
