# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import matecat_api
from matecat_api.api.teams_api import TeamsApi  # noqa: E501
from matecat_api.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v2_teams_get(self):
        """Test case for api_v2_teams_get

        List available teams  # noqa: E501
        """
        pass

    def test_api_v2_teams_id_team_members_get(self):
        """Test case for api_v2_teams_id_team_members_get

        List team members  # noqa: E501
        """
        pass

    def test_api_v2_teams_id_team_members_id_member_delete(self):
        """Test case for api_v2_teams_id_team_members_id_member_delete

        List team members  # noqa: E501
        """
        pass

    def test_api_v2_teams_id_team_members_post(self):
        """Test case for api_v2_teams_id_team_members_post

        Create new team memberships  # noqa: E501
        """
        pass

    def test_api_v2_teams_id_team_projects_get(self):
        """Test case for api_v2_teams_id_team_projects_get

        Get the list of projects in a team  # noqa: E501
        """
        pass

    def test_api_v2_teams_id_team_projects_id_project_get(self):
        """Test case for api_v2_teams_id_team_projects_id_project_get

        Get a project in a team scope  # noqa: E501
        """
        pass

    def test_api_v2_teams_id_team_projects_id_project_put(self):
        """Test case for api_v2_teams_id_team_projects_id_project_put

        Update a team's project  # noqa: E501
        """
        pass

    def test_api_v2_teams_id_team_projects_project_name_get(self):
        """Test case for api_v2_teams_id_team_projects_project_name_get

        Get projects in a team scope  # noqa: E501
        """
        pass

    def test_api_v2_teams_id_team_put(self):
        """Test case for api_v2_teams_id_team_put

        Update team  # noqa: E501
        """
        pass

    def test_api_v2_teams_post(self):
        """Test case for api_v2_teams_post

        Create a new team  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
