# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import matecat_api
from matecat_api.api.job_api import JobApi  # noqa: E501
from matecat_api.rest import ApiException


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_jobs_id_job_password_stats_get(self):
        """Test case for api_v1_jobs_id_job_password_stats_get

        Statistics  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_active_post(self):
        """Test case for api_v2_jobs_id_job_password_active_post

        Active API  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_archive_post(self):
        """Test case for api_v2_jobs_id_job_password_archive_post

        Archive API  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_cancel_post(self):
        """Test case for api_v2_jobs_id_job_password_cancel_post

        Cancel API  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_comments_get(self):
        """Test case for api_v2_jobs_id_job_password_comments_get

        Get segment comments in a job  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_get(self):
        """Test case for api_v2_jobs_id_job_password_get

        Job Info  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_options_post(self):
        """Test case for api_v2_jobs_id_job_password_options_post

        Update Options  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_quality_report_get(self):
        """Test case for api_v2_jobs_id_job_password_quality_report_get

        Quality report  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_segments_id_segment_translation_issues_id_issue_comments_get(self):
        """Test case for api_v2_jobs_id_job_password_segments_id_segment_translation_issues_id_issue_comments_get

        Get comments  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_segments_id_segment_translation_issues_id_issue_comments_post(self):
        """Test case for api_v2_jobs_id_job_password_segments_id_segment_translation_issues_id_issue_comments_post

        Add comment to a translation issue  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_segments_id_segment_translation_issues_id_issue_delete(self):
        """Test case for api_v2_jobs_id_job_password_segments_id_segment_translation_issues_id_issue_delete

        Delete a translation Issue  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_segments_id_segment_translation_issues_id_issue_post(self):
        """Test case for api_v2_jobs_id_job_password_segments_id_segment_translation_issues_id_issue_post

        Update translation issues  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_segments_id_segment_translation_issues_post(self):
        """Test case for api_v2_jobs_id_job_password_segments_id_segment_translation_issues_post

        Create translation issues  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_segments_id_segment_translation_versions_get(self):
        """Test case for api_v2_jobs_id_job_password_segments_id_segment_translation_versions_get

        Segment versions  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_segments_id_segment_translation_versions_version_number_get(self):
        """Test case for api_v2_jobs_id_job_password_segments_id_segment_translation_versions_version_number_get

        Get a Segment translation version  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_translation_issues_get(self):
        """Test case for api_v2_jobs_id_job_password_translation_issues_get

        Project translation issues  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_translation_versions_get(self):
        """Test case for api_v2_jobs_id_job_password_translation_versions_get

        Project translation versions  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_translator_get(self):
        """Test case for api_v2_jobs_id_job_password_translator_get

        Gets the translator assigned to a job  # noqa: E501
        """
        pass

    def test_api_v2_jobs_id_job_password_translator_post(self):
        """Test case for api_v2_jobs_id_job_password_translator_post

        Assigns a job to a translator  # noqa: E501
        """
        pass

    def test_t_mx_id_job_password_post(self):
        """Test case for t_mx_id_job_password_post

        Download Job TMX  # noqa: E501
        """
        pass

    def test_translation_id_job_password_get(self):
        """Test case for translation_id_job_password_get

        Download Translation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
