# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import matecat_api
from matecat_api.models.urls_job import UrlsJob  # noqa: E501
from matecat_api.rest import ApiException


class TestUrlsJob(unittest.TestCase):
    """UrlsJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUrlsJob(self):
        """Test UrlsJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = matecat_api.models.urls_job.UrlsJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
