# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body14(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'files': 'str',
        'name': 'str',
        'tm_key': 'str'
    }

    attribute_map = {
        'files': 'files',
        'name': 'name',
        'tm_key': 'tm_key'
    }

    def __init__(self, files=None, name=None, tm_key=None):  # noqa: E501
        """Body14 - a model defined in Swagger"""  # noqa: E501
        self._files = None
        self._name = None
        self._tm_key = None
        self.discriminator = None
        self.files = files
        if name is not None:
            self.name = name
        if tm_key is not None:
            self.tm_key = tm_key

    @property
    def files(self):
        """Gets the files of this Body14.  # noqa: E501

        The file(s) to be uploaded  # noqa: E501

        :return: The files of this Body14.  # noqa: E501
        :rtype: str
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this Body14.

        The file(s) to be uploaded  # noqa: E501

        :param files: The files of this Body14.  # noqa: E501
        :type: str
        """
        if files is None:
            raise ValueError("Invalid value for `files`, must not be `None`")  # noqa: E501

        self._files = files

    @property
    def name(self):
        """Gets the name of this Body14.  # noqa: E501

        The file name.  # noqa: E501

        :return: The name of this Body14.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Body14.

        The file name.  # noqa: E501

        :param name: The name of this Body14.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def tm_key(self):
        """Gets the tm_key of this Body14.  # noqa: E501

        The tm key.  # noqa: E501

        :return: The tm_key of this Body14.  # noqa: E501
        :rtype: str
        """
        return self._tm_key

    @tm_key.setter
    def tm_key(self, tm_key):
        """Sets the tm_key of this Body14.

        The tm key.  # noqa: E501

        :param tm_key: The tm_key of this Body14.  # noqa: E501
        :type: str
        """

        self._tm_key = tm_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body14, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body14):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
