# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body11(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rebutted_at': 'str'
    }

    attribute_map = {
        'rebutted_at': 'rebutted_at'
    }

    def __init__(self, rebutted_at=None):  # noqa: E501
        """Body11 - a model defined in Swagger"""  # noqa: E501
        self._rebutted_at = None
        self.discriminator = None
        self.rebutted_at = rebutted_at

    @property
    def rebutted_at(self):
        """Gets the rebutted_at of this Body11.  # noqa: E501


        :return: The rebutted_at of this Body11.  # noqa: E501
        :rtype: str
        """
        return self._rebutted_at

    @rebutted_at.setter
    def rebutted_at(self, rebutted_at):
        """Sets the rebutted_at of this Body11.


        :param rebutted_at: The rebutted_at of this Body11.  # noqa: E501
        :type: str
        """
        if rebutted_at is None:
            raise ValueError("Invalid value for `rebutted_at`, must not be `None`")  # noqa: E501

        self._rebutted_at = rebutted_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body11, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body11):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
