# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body9(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id_assignee': 'int',
        'id_team': 'int',
        'name': 'str'
    }

    attribute_map = {
        'id_assignee': 'id_assignee',
        'id_team': 'id_team',
        'name': 'name'
    }

    def __init__(self, id_assignee=None, id_team=None, name=None):  # noqa: E501
        """Body9 - a model defined in Swagger"""  # noqa: E501
        self._id_assignee = None
        self._id_team = None
        self._name = None
        self.discriminator = None
        if id_assignee is not None:
            self.id_assignee = id_assignee
        if id_team is not None:
            self.id_team = id_team
        if name is not None:
            self.name = name

    @property
    def id_assignee(self):
        """Gets the id_assignee of this Body9.  # noqa: E501


        :return: The id_assignee of this Body9.  # noqa: E501
        :rtype: int
        """
        return self._id_assignee

    @id_assignee.setter
    def id_assignee(self, id_assignee):
        """Sets the id_assignee of this Body9.


        :param id_assignee: The id_assignee of this Body9.  # noqa: E501
        :type: int
        """

        self._id_assignee = id_assignee

    @property
    def id_team(self):
        """Gets the id_team of this Body9.  # noqa: E501


        :return: The id_team of this Body9.  # noqa: E501
        :rtype: int
        """
        return self._id_team

    @id_team.setter
    def id_team(self, id_team):
        """Sets the id_team of this Body9.


        :param id_team: The id_team of this Body9.  # noqa: E501
        :type: int
        """

        self._id_team = id_team

    @property
    def name(self):
        """Gets the name of this Body9.  # noqa: E501


        :return: The name of this Body9.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Body9.


        :param name: The name of this Body9.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body9, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body9):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
