# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id_project': 'int',
        'old_pass': 'str',
        'new_pass': 'str'
    }

    attribute_map = {
        'id_project': 'id_project',
        'old_pass': 'old_pass',
        'new_pass': 'new_pass'
    }

    def __init__(self, id_project=None, old_pass=None, new_pass=None):  # noqa: E501
        """Body1 - a model defined in Swagger"""  # noqa: E501
        self._id_project = None
        self._old_pass = None
        self._new_pass = None
        self.discriminator = None
        self.id_project = id_project
        self.old_pass = old_pass
        self.new_pass = new_pass

    @property
    def id_project(self):
        """Gets the id_project of this Body1.  # noqa: E501

        The id of the project you want to update.  # noqa: E501

        :return: The id_project of this Body1.  # noqa: E501
        :rtype: int
        """
        return self._id_project

    @id_project.setter
    def id_project(self, id_project):
        """Sets the id_project of this Body1.

        The id of the project you want to update.  # noqa: E501

        :param id_project: The id_project of this Body1.  # noqa: E501
        :type: int
        """
        if id_project is None:
            raise ValueError("Invalid value for `id_project`, must not be `None`")  # noqa: E501

        self._id_project = id_project

    @property
    def old_pass(self):
        """Gets the old_pass of this Body1.  # noqa: E501

        The OLD password of the project you want to update.  # noqa: E501

        :return: The old_pass of this Body1.  # noqa: E501
        :rtype: str
        """
        return self._old_pass

    @old_pass.setter
    def old_pass(self, old_pass):
        """Sets the old_pass of this Body1.

        The OLD password of the project you want to update.  # noqa: E501

        :param old_pass: The old_pass of this Body1.  # noqa: E501
        :type: str
        """
        if old_pass is None:
            raise ValueError("Invalid value for `old_pass`, must not be `None`")  # noqa: E501

        self._old_pass = old_pass

    @property
    def new_pass(self):
        """Gets the new_pass of this Body1.  # noqa: E501

        The NEW password of the project you want to update.  # noqa: E501

        :return: The new_pass of this Body1.  # noqa: E501
        :rtype: str
        """
        return self._new_pass

    @new_pass.setter
    def new_pass(self, new_pass):
        """Sets the new_pass of this Body1.

        The NEW password of the project you want to update.  # noqa: E501

        :param new_pass: The new_pass of this Body1.  # noqa: E501
        :type: str
        """
        if new_pass is None:
            raise ValueError("Invalid value for `new_pass`, must not be `None`")  # noqa: E501

        self._new_pass = new_pass

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
