# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KeysList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'private_keys': 'list[Key]',
        'shared_keys': 'list[Key]'
    }

    attribute_map = {
        'private_keys': 'private_keys',
        'shared_keys': 'shared_keys'
    }

    def __init__(self, private_keys=None, shared_keys=None):  # noqa: E501
        """KeysList - a model defined in Swagger"""  # noqa: E501
        self._private_keys = None
        self._shared_keys = None
        self.discriminator = None
        if private_keys is not None:
            self.private_keys = private_keys
        if shared_keys is not None:
            self.shared_keys = shared_keys

    @property
    def private_keys(self):
        """Gets the private_keys of this KeysList.  # noqa: E501


        :return: The private_keys of this KeysList.  # noqa: E501
        :rtype: list[Key]
        """
        return self._private_keys

    @private_keys.setter
    def private_keys(self, private_keys):
        """Sets the private_keys of this KeysList.


        :param private_keys: The private_keys of this KeysList.  # noqa: E501
        :type: list[Key]
        """

        self._private_keys = private_keys

    @property
    def shared_keys(self):
        """Gets the shared_keys of this KeysList.  # noqa: E501


        :return: The shared_keys of this KeysList.  # noqa: E501
        :rtype: list[Key]
        """
        return self._shared_keys

    @shared_keys.setter
    def shared_keys(self, shared_keys):
        """Sets the shared_keys of this KeysList.


        :param shared_keys: The shared_keys of this KeysList.  # noqa: E501
        :type: list[Key]
        """

        self._shared_keys = shared_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeysList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeysList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
