# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Language(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'name': 'str',
        'direction': 'str'
    }

    attribute_map = {
        'code': 'code',
        'name': 'name',
        'direction': 'direction'
    }

    def __init__(self, code=None, name=None, direction=None):  # noqa: E501
        """Language - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._name = None
        self._direction = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if name is not None:
            self.name = name
        if direction is not None:
            self.direction = direction

    @property
    def code(self):
        """Gets the code of this Language.  # noqa: E501

        Rfc code  # noqa: E501

        :return: The code of this Language.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Language.

        Rfc code  # noqa: E501

        :param code: The code of this Language.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def name(self):
        """Gets the name of this Language.  # noqa: E501

        Language name  # noqa: E501

        :return: The name of this Language.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Language.

        Language name  # noqa: E501

        :param name: The name of this Language.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def direction(self):
        """Gets the direction of this Language.  # noqa: E501

        Language direction, ltr (left-to-right text) or rtl (right-to-left text)  # noqa: E501

        :return: The direction of this Language.  # noqa: E501
        :rtype: str
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """Sets the direction of this Language.

        Language direction, ltr (left-to-right text) or rtl (right-to-left text)  # noqa: E501

        :param direction: The direction of this Language.  # noqa: E501
        :type: str
        """
        allowed_values = ["ltr", "rtl"]  # noqa: E501
        if direction not in allowed_values:
            raise ValueError(
                "Invalid value for `direction` ({0}), must be one of {1}"  # noqa: E501
                .format(direction, allowed_values)
            )

        self._direction = direction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Language, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Language):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
