# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectCreationStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'message': 'str',
        'id_project': 'int',
        'project_pass': 'str',
        'project_name': 'str',
        'new_keys': 'str',
        'analyze_url': 'str'
    }

    attribute_map = {
        'status': 'status',
        'message': 'message',
        'id_project': 'id_project',
        'project_pass': 'project_pass',
        'project_name': 'project_name',
        'new_keys': 'new_keys',
        'analyze_url': 'analyze_url'
    }

    def __init__(self, status=None, message=None, id_project=None, project_pass=None, project_name=None, new_keys=None, analyze_url=None):  # noqa: E501
        """ProjectCreationStatus - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._message = None
        self._id_project = None
        self._project_pass = None
        self._project_name = None
        self._new_keys = None
        self._analyze_url = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if message is not None:
            self.message = message
        if id_project is not None:
            self.id_project = id_project
        if project_pass is not None:
            self.project_pass = project_pass
        if project_name is not None:
            self.project_name = project_name
        if new_keys is not None:
            self.new_keys = new_keys
        if analyze_url is not None:
            self.analyze_url = analyze_url

    @property
    def status(self):
        """Gets the status of this ProjectCreationStatus.  # noqa: E501


        :return: The status of this ProjectCreationStatus.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ProjectCreationStatus.


        :param status: The status of this ProjectCreationStatus.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def message(self):
        """Gets the message of this ProjectCreationStatus.  # noqa: E501


        :return: The message of this ProjectCreationStatus.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ProjectCreationStatus.


        :param message: The message of this ProjectCreationStatus.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def id_project(self):
        """Gets the id_project of this ProjectCreationStatus.  # noqa: E501


        :return: The id_project of this ProjectCreationStatus.  # noqa: E501
        :rtype: int
        """
        return self._id_project

    @id_project.setter
    def id_project(self, id_project):
        """Sets the id_project of this ProjectCreationStatus.


        :param id_project: The id_project of this ProjectCreationStatus.  # noqa: E501
        :type: int
        """

        self._id_project = id_project

    @property
    def project_pass(self):
        """Gets the project_pass of this ProjectCreationStatus.  # noqa: E501


        :return: The project_pass of this ProjectCreationStatus.  # noqa: E501
        :rtype: str
        """
        return self._project_pass

    @project_pass.setter
    def project_pass(self, project_pass):
        """Sets the project_pass of this ProjectCreationStatus.


        :param project_pass: The project_pass of this ProjectCreationStatus.  # noqa: E501
        :type: str
        """

        self._project_pass = project_pass

    @property
    def project_name(self):
        """Gets the project_name of this ProjectCreationStatus.  # noqa: E501


        :return: The project_name of this ProjectCreationStatus.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this ProjectCreationStatus.


        :param project_name: The project_name of this ProjectCreationStatus.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def new_keys(self):
        """Gets the new_keys of this ProjectCreationStatus.  # noqa: E501


        :return: The new_keys of this ProjectCreationStatus.  # noqa: E501
        :rtype: str
        """
        return self._new_keys

    @new_keys.setter
    def new_keys(self, new_keys):
        """Sets the new_keys of this ProjectCreationStatus.


        :param new_keys: The new_keys of this ProjectCreationStatus.  # noqa: E501
        :type: str
        """

        self._new_keys = new_keys

    @property
    def analyze_url(self):
        """Gets the analyze_url of this ProjectCreationStatus.  # noqa: E501


        :return: The analyze_url of this ProjectCreationStatus.  # noqa: E501
        :rtype: str
        """
        return self._analyze_url

    @analyze_url.setter
    def analyze_url(self, analyze_url):
        """Sets the analyze_url of this ProjectCreationStatus.


        :param analyze_url: The analyze_url of this ProjectCreationStatus.  # noqa: E501
        :type: str
        """

        self._analyze_url = analyze_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectCreationStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectCreationStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
