# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QualityReport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'chunk': 'object',
        'job': 'object',
        'project': 'object'
    }

    attribute_map = {
        'chunk': 'chunk',
        'job': 'job',
        'project': 'project'
    }

    def __init__(self, chunk=None, job=None, project=None):  # noqa: E501
        """QualityReport - a model defined in Swagger"""  # noqa: E501
        self._chunk = None
        self._job = None
        self._project = None
        self.discriminator = None
        if chunk is not None:
            self.chunk = chunk
        if job is not None:
            self.job = job
        if project is not None:
            self.project = project

    @property
    def chunk(self):
        """Gets the chunk of this QualityReport.  # noqa: E501


        :return: The chunk of this QualityReport.  # noqa: E501
        :rtype: object
        """
        return self._chunk

    @chunk.setter
    def chunk(self, chunk):
        """Sets the chunk of this QualityReport.


        :param chunk: The chunk of this QualityReport.  # noqa: E501
        :type: object
        """

        self._chunk = chunk

    @property
    def job(self):
        """Gets the job of this QualityReport.  # noqa: E501


        :return: The job of this QualityReport.  # noqa: E501
        :rtype: object
        """
        return self._job

    @job.setter
    def job(self, job):
        """Sets the job of this QualityReport.


        :param job: The job of this QualityReport.  # noqa: E501
        :type: object
        """

        self._job = job

    @property
    def project(self):
        """Gets the project of this QualityReport.  # noqa: E501


        :return: The project of this QualityReport.  # noqa: E501
        :rtype: object
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this QualityReport.


        :param project: The project of this QualityReport.  # noqa: E501
        :type: object
        """

        self._project = project

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QualityReport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QualityReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
