# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UploadGlossaryStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'done': 'int',
        'total': 'int',
        'source_lang': 'str',
        'target_lang': 'str',
        'completed': 'bool'
    }

    attribute_map = {
        'done': 'done',
        'total': 'total',
        'source_lang': 'source_lang',
        'target_lang': 'target_lang',
        'completed': 'completed'
    }

    def __init__(self, done=None, total=None, source_lang=None, target_lang=None, completed=None):  # noqa: E501
        """UploadGlossaryStatus - a model defined in Swagger"""  # noqa: E501
        self._done = None
        self._total = None
        self._source_lang = None
        self._target_lang = None
        self._completed = None
        self.discriminator = None
        if done is not None:
            self.done = done
        if total is not None:
            self.total = total
        if source_lang is not None:
            self.source_lang = source_lang
        if target_lang is not None:
            self.target_lang = target_lang
        if completed is not None:
            self.completed = completed

    @property
    def done(self):
        """Gets the done of this UploadGlossaryStatus.  # noqa: E501


        :return: The done of this UploadGlossaryStatus.  # noqa: E501
        :rtype: int
        """
        return self._done

    @done.setter
    def done(self, done):
        """Sets the done of this UploadGlossaryStatus.


        :param done: The done of this UploadGlossaryStatus.  # noqa: E501
        :type: int
        """

        self._done = done

    @property
    def total(self):
        """Gets the total of this UploadGlossaryStatus.  # noqa: E501


        :return: The total of this UploadGlossaryStatus.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this UploadGlossaryStatus.


        :param total: The total of this UploadGlossaryStatus.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def source_lang(self):
        """Gets the source_lang of this UploadGlossaryStatus.  # noqa: E501


        :return: The source_lang of this UploadGlossaryStatus.  # noqa: E501
        :rtype: str
        """
        return self._source_lang

    @source_lang.setter
    def source_lang(self, source_lang):
        """Sets the source_lang of this UploadGlossaryStatus.


        :param source_lang: The source_lang of this UploadGlossaryStatus.  # noqa: E501
        :type: str
        """

        self._source_lang = source_lang

    @property
    def target_lang(self):
        """Gets the target_lang of this UploadGlossaryStatus.  # noqa: E501


        :return: The target_lang of this UploadGlossaryStatus.  # noqa: E501
        :rtype: str
        """
        return self._target_lang

    @target_lang.setter
    def target_lang(self, target_lang):
        """Sets the target_lang of this UploadGlossaryStatus.


        :param target_lang: The target_lang of this UploadGlossaryStatus.  # noqa: E501
        :type: str
        """

        self._target_lang = target_lang

    @property
    def completed(self):
        """Gets the completed of this UploadGlossaryStatus.  # noqa: E501


        :return: The completed of this UploadGlossaryStatus.  # noqa: E501
        :rtype: bool
        """
        return self._completed

    @completed.setter
    def completed(self, completed):
        """Sets the completed of this UploadGlossaryStatus.


        :param completed: The completed of this UploadGlossaryStatus.  # noqa: E501
        :type: bool
        """

        self._completed = completed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UploadGlossaryStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UploadGlossaryStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
