# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UrlsJob(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'target_lang': 'str',
        'chunks': 'list[Url]'
    }

    attribute_map = {
        'id': 'id',
        'target_lang': 'target_lang',
        'chunks': 'chunks'
    }

    def __init__(self, id=None, target_lang=None, chunks=None):  # noqa: E501
        """UrlsJob - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._target_lang = None
        self._chunks = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if target_lang is not None:
            self.target_lang = target_lang
        if chunks is not None:
            self.chunks = chunks

    @property
    def id(self):
        """Gets the id of this UrlsJob.  # noqa: E501


        :return: The id of this UrlsJob.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UrlsJob.


        :param id: The id of this UrlsJob.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def target_lang(self):
        """Gets the target_lang of this UrlsJob.  # noqa: E501


        :return: The target_lang of this UrlsJob.  # noqa: E501
        :rtype: str
        """
        return self._target_lang

    @target_lang.setter
    def target_lang(self, target_lang):
        """Sets the target_lang of this UrlsJob.


        :param target_lang: The target_lang of this UrlsJob.  # noqa: E501
        :type: str
        """

        self._target_lang = target_lang

    @property
    def chunks(self):
        """Gets the chunks of this UrlsJob.  # noqa: E501


        :return: The chunks of this UrlsJob.  # noqa: E501
        :rtype: list[Url]
        """
        return self._chunks

    @chunks.setter
    def chunks(self, chunks):
        """Sets the chunks of this UrlsJob.


        :param chunks: The chunks of this UrlsJob.  # noqa: E501
        :type: list[Url]
        """

        self._chunks = chunks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UrlsJob, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UrlsJob):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
