# coding: utf-8

"""
    MateCat API

    We developed a set of Rest API to let you integrate Matecat in your translation management system or in any other application. Use our API to create projects and check their status.  # noqa: E501

    OpenAPI spec version: 2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Urls(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'files': 'Files',
        'jobs': 'UrlsJobs'
    }

    attribute_map = {
        'files': 'files',
        'jobs': 'jobs'
    }

    def __init__(self, files=None, jobs=None):  # noqa: E501
        """Urls - a model defined in Swagger"""  # noqa: E501
        self._files = None
        self._jobs = None
        self.discriminator = None
        if files is not None:
            self.files = files
        if jobs is not None:
            self.jobs = jobs

    @property
    def files(self):
        """Gets the files of this Urls.  # noqa: E501


        :return: The files of this Urls.  # noqa: E501
        :rtype: Files
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this Urls.


        :param files: The files of this Urls.  # noqa: E501
        :type: Files
        """

        self._files = files

    @property
    def jobs(self):
        """Gets the jobs of this Urls.  # noqa: E501


        :return: The jobs of this Urls.  # noqa: E501
        :rtype: UrlsJobs
        """
        return self._jobs

    @jobs.setter
    def jobs(self, jobs):
        """Sets the jobs of this Urls.


        :param jobs: The jobs of this Urls.  # noqa: E501
        :type: UrlsJobs
        """

        self._jobs = jobs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Urls, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Urls):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
